### ISSUE TITLE
Get ScriptingQueryEngine - NoSuchBeanDefinitionException

### ISSUE THREAD

**Issue by cptwunderlich** [rpau/walkmod-core#45]
While trying to test the example from http://walkmod.com/manual#script,
I get an exception. (See stacktrace at the end)
Walkmod version is `2.0.1`

Please take a look at `org.walkmod.conf.entities.impl.ConfigurationImpl.getBean(String, Map<?, ?>)`
In `ScriptProcessor` the method invocation is `context.getBean("org.walkmod.query.ScriptingQueryEngine", parameters);`.

Now in "getBean" it might go into the first if-block (I have troubles getting my dev environment to work and can't step in with the debugger)

		if (beanFactory != null && beanFactory.containsBean(name)) {
			result = beanFactory.getBean(name);
		}

But the next if-block is not an 'else' statement, it is:

		if (!name.contains(":")) {
			result = beanFactory.getBean("org.walkmod:walkmod-" + name + "-plugin:" + name);
		}

So it could overwrite `result`. Also, as seen in the stacktrace, the String with "-plugin" etc is being constructed, while the class to be loaded is simply a local class and the simpler "org.walkmod.query.ScriptingQueryEngine" should suffice. Or am I missing something?

    ERROR [main] - TRANSFORMATION CHAIN (example-chain) FAILS
    An exeception has been produced during the null transformation - org.walkmod.util.location.LocationImpl@4de41af9
            at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
            at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
            at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
            at java.lang.reflect.Method.invoke(Method.java:497)
            at org.walkmod.walkers.AbstractWalker.walk(AbstractWalker.java:250)
            at org.walkmod.walkers.AbstractWalker.execute(AbstractWalker.java:265)
            at org.walkmod.impl.DefaultChainWalkerInvocation.invoke(DefaultChainWalkerInvocation.java:41)
            at org.walkmod.impl.DefaultChainInvocation.invoke(DefaultChainInvocation.java:38)
            at org.walkmod.impl.DefaultChainAdapter.execute(DefaultChainAdapter.java:165)
            at org.walkmod.WalkModFacade.executeAllChains(WalkModFacade.java:904)
            at org.walkmod.WalkModFacade.apply(WalkModFacade.java:375)
            at org.walkmod.commands.ApplyCommand.execute(ApplyCommand.java:40)
            at org.walkmod.WalkModDispatcher.execute(WalkModDispatcher.java:164)
            at org.walkmod.WalkModDispatcher.main(WalkModDispatcher.java:189)
    Caused by: java.lang.reflect.InvocationTargetException
            ... 14 more
    Caused by: java.lang.reflect.InvocationTargetException
            at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
            at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
            at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
            at java.lang.reflect.Method.invoke(Method.java:497)
            at org.walkmod.walkers.AbstractWalker.visit(AbstractWalker.java:112)
            at org.walkmod.walkers.AbstractWalker.visit(AbstractWalker.java:161)
            at org.walkmod.javalang.walkers.DefaultJavaWalker.visit(DefaultJavaWalker.java:332)
            at org.walkmod.javalang.walkers.DefaultJavaWalker.visit(DefaultJavaWalker.java:127)
            at org.walkmod.javalang.walkers.DefaultJavaWalker.accept(DefaultJavaWalker.java:74)
            ... 14 more
    Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'org.walkmod:walkmod-org.walkmod.query.ScriptingQueryEngine-plugin:org.walkmod.query.ScriptingQueryEngine' is defined
            at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanDefinition(DefaultListableBeanFactory.java:529)
            at org.springframework.beans.factory.support.AbstractBeanFactory.getMergedLocalBeanDefinition(AbstractBeanFactory.java:1095)
            at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:277)
            at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:193)
            at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1093)
            at org.walkmod.conf.entities.impl.ConfigurationImpl.getBean(ConfigurationImpl.java:137)
            at org.walkmod.walkers.VisitorContext.getBean(VisitorContext.java:119)
            at org.walkmod.scripting.ScriptProcessor.initialize(ScriptProcessor.java:74)
            at org.walkmod.scripting.ScriptProcessor.visit(ScriptProcessor.java:91)
            ... 23 more

**Comment by rpau** [comment]
Thank you! I am going to try to solve it now :)

**Comment by rpau** [comment]
@cptwunderlich It was the problem that you found. However, writing a test I have found other related issues that also have been solved :)

**Comment by cptwunderlich** [comment]
I did a quick test with the original test project and it works now!

**Comment by rpau** [comment]
Great! :) and thank you again to giving us feedback
